const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const path=require('node:path'),http=require('node:http');
const assets=path.resolve(__dirname,'../app/src/main/assets/ui'),out=path.resolve(__dirname,'../build/ui-qa');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const file=path.resolve(assets,'.'+(new URL(req.url,'http://localhost').pathname==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));if(!file.startsWith(assets+path.sep)){res.writeHead(403).end();return;}try{const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json'};res.setHeader('Content-Type',mime[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{
 await new Promise(resolve=>server.listen(8765,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.emulateMedia({colorScheme:'light'});await page.goto('http://127.0.0.1:8765');await page.locator('[data-country=PL]').waitFor();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await page.getByRole('button',{name:'Ustawienia'}).click();assert.equal(await page.locator('[data-theme-choice]').count(),2);assert.equal(await page.getByRole('button',{name:'System',exact:true}).count(),0);await page.getByRole('button',{name:'Light',exact:true}).click();await page.locator('#closeSettings').click();await page.reload();await page.locator('[data-country=PL]').waitFor();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.evaluate(()=>localStorage.setItem('theme','system'));await page.reload();await page.locator('[data-country=PL]').waitFor();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 await page.getByRole('button',{name:'Ustawienia'}).click();await page.locator('#openBackup').click();await page.evaluate(()=>{window.backupCalls=[];window.Passport={exportBackup:()=>backupCalls.push('export'),importBackup:()=>backupCalls.push('import'),confirmImport:t=>backupCalls.push(t)};});await page.locator('#exportBackup').click();assert(await page.locator('#exportBackup').isDisabled());await page.evaluate(()=>backupEvent({type:'cancelled',message:'Anulowano wybór pliku.'}));assert(!await page.locator('#exportBackup').isDisabled());await page.locator('#importBackup').click();await page.evaluate(()=>backupEvent({type:'preview',newVisits:2,newPlans:1,skippedVisits:3,skippedPlans:0,photos:4,theme:'dark',country:'PL',token:'confirmed-token'}));assert.deepEqual(await page.evaluate(()=>backupCalls),['export','import']);assert(await page.locator('#backupStatus').innerText().then(t=>t.includes('Nowe wizyty: 2')));await page.screenshot({path:path.join(out,'backup-preview.png')});await page.locator('#confirmBackupImport').click();assert.deepEqual(await page.evaluate(()=>backupCalls),['export','import','confirmed-token']);await page.evaluate(()=>backupEvent({type:'error',message:'Nie zmieniono danych.'}));assert(!await page.locator('#importBackup').isDisabled());assert.equal(await page.evaluate(()=>visits.length),0);await page.setViewportSize({width:320,height:640});assert(await page.evaluate(()=>backupDialog.scrollWidth<=backupDialog.clientWidth));assert.deepEqual(errors,[]);console.log('PASS: Dark default/system migration/Light persistence; backup chooser/cancel/preview/explicit confirmation/error; mobile');await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
