const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const path=require('node:path'),http=require('node:http');
const assets=path.resolve(__dirname,'../app/src/main/assets/ui'),out=path.resolve(__dirname,'../build/ui-qa');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const file=path.resolve(assets,'.'+(new URL(req.url,'http://localhost').pathname==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));if(!file.startsWith(assets+path.sep)){res.writeHead(403).end();return;}try{const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json'};res.setHeader('Content-Type',mime[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{
 const engine=require('../app/src/main/assets/ui/achievement-engine.js');const config=JSON.parse(fs.readFileSync(path.join(assets,'achievements.json'),'utf8'));assert.equal(config.approved,false);assert.equal(config.tiers.length,11);for(const f of config.families){assert.equal(f.thresholds.length,11);assert(f.thresholds.every((n,i)=>i===0||n>f.thresholds[i-1]));}
 const places=[{id:'p',country:'PL',mapReady:true,category:'peak'},{id:'d',country:'DE',mapReady:true,category:'peak'}],visits=[{placeId:'p',distance_m:1000,duration_minutes:30},{placeId:'p',distance_m:2000,duration_minutes:60},{placeId:'d',distance_m:9000}];assert.equal(engine.value(config.families.find(f=>f.id==='peak'),'PL',places,visits,[]),1);assert.equal(engine.value(config.families.find(f=>f.id==='distance'),'PL',places,visits,[]),3);assert.equal(engine.value(config.families.find(f=>f.id==='time'),'PL',places,visits,[]),1.5);assert.equal(engine.tier(0,[1,3]),-1);assert.equal(engine.tier(3,[1,3]),1);
 await new Promise(resolve=>server.listen(8765,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765');await page.locator('[data-country=PL]').click();await page.locator('[data-tab=achievements]').click();await page.locator('[data-badge=peak]').waitFor();assert.equal(await page.locator('[data-badge]').count(),12);await page.screenshot({path:path.join(out,'badges-dark.png')});await page.locator('[data-badge=peak]').click();assert.equal(await page.locator('[data-tier]').count(),11);await page.locator('[data-tier="10"]').click();assert.equal(await page.locator('.badge-hero .badge-level').innerText(),'Master ★★★');await page.screenshot({path:path.join(out,'badge-ladder-dark.png')});await page.locator('[data-detail-close]').click();await page.getByRole('button',{name:'Ustawienia',exact:true}).click();await page.getByRole('button',{name:'Light',exact:true}).click();await page.locator('#closeSettings').click();await page.locator('[data-achievement-country=DE]').click();await page.locator('[data-badge=peak]').waitFor();assert.equal(await page.evaluate(()=>country),'DE');await page.screenshot({path:path.join(out,'badges-light.png')});await page.setViewportSize({width:320,height:640});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('PASS: 12 family previews, 11 tiers each, unique places vs sums, country isolation, exact boundaries, Light/Dark, no awards before approval');await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
