const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const assets=path.resolve(__dirname,'../app/src/main/assets/ui'),out=path.resolve(__dirname,'../build/ui-qa');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{let file=path.resolve(assets,'.'+(req.url==='/'?'/index.html':req.url));if(!file.startsWith(assets+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(8766,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});
try{const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8766');await page.locator('[data-country=DE]').click();
await page.evaluate(()=>{const p=catalog.places.find(p=>p.country==='DE'&&p.mapReady&&p.category==='peak');visits=[{id:crypto.randomUUID(),placeId:p.id,date:'2026-09-01',rating:5,weather:'Śnieg',notes:'Zachowana notatka',trailUrl:'Trasa tekstowa',distance_m:1200,duration_minutes:90,elevation_gain_m:100,photos:[]}];localStorage.setItem('visits',JSON.stringify(visits));visited=new Set(visits.map(v=>v.placeId));});
await page.locator('[data-tab=journal]').click();assert.equal(await page.locator('.journal .legacy-visit').count(),1);assert.equal(await page.locator('.journal-rating').getAttribute('aria-label'),'Ocena 5 z 5');
await page.locator('[data-edit-visit]').click();await page.locator('#cancelVisit').click();assert.equal(await page.locator('.journal .legacy-visit').count(),1);
await page.locator('[data-edit-visit]').click();assert.equal(await page.locator('[data-rating]').count(),10);
for(const [n,tone] of [[1,'low'],[3,'low'],[4,'medium'],[6,'medium'],[7,'high'],[9,'high'],[10,'diamond']]){await page.locator(`[data-rating="${n}"]`).click();assert((await page.locator('.rating-choices').getAttribute('class')).includes(tone));}
await page.screenshot({path:path.join(out,'visit112-dark.png')});await page.getByRole('button',{name:'Zapisz wizytę',exact:true}).click();assert.equal(await page.locator('.journal .legacy-visit').count(),0);assert.equal(await page.locator('.journal-rating').getAttribute('aria-label'),'Ocena 10 z 10');assert.equal(await page.evaluate(()=>visits[0].notes),'Zachowana notatka');assert.equal(await page.evaluate(()=>visits[0].formVersion),2);
const actions=await page.locator('.journal-actions').evaluate(e=>getComputedStyle(e).justifyContent);assert.equal(actions,'flex-end');assert.equal(await page.locator('[data-edit-visit] svg').count(),1);
await page.reload();await page.locator('[data-tab=journal]').click();assert.equal(await page.locator('.journal .legacy-visit').count(),0);await page.selectOption('#journalRating','10');assert.equal(await page.locator('.journal article').count(),1);
await page.screenshot({path:path.join(out,'journal112-dark.png')});await page.evaluate(()=>document.documentElement.dataset.theme='light');await page.setViewportSize({width:320,height:780});await page.screenshot({path:path.join(out,'journal112-light-320.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.locator('[data-tab=collections]').click();await page.locator('[data-collection-mode=plans]').click();assert((await page.locator('#newPlan').innerText()).includes('Dodaj własną Wycieczkę'));
assert.deepEqual(errors,[]);console.log('PASS: legacy prompt/cancel/resave, 10 ratings and boundary colors, preservation, reload/filter, pencil/right actions, trips, 320px layout');
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
