const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const path=require('node:path'),http=require('node:http');
const assets=path.resolve(__dirname,'../app/src/main/assets/ui'),out=path.resolve(__dirname,'../build/ui-qa');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const file=path.resolve(assets,'.'+(new URL(req.url,'http://localhost').pathname==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));if(!file.startsWith(assets+path.sep)){res.writeHead(403).end();return;}try{const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json'};res.setHeader('Content-Type',mime[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{
 await new Promise(resolve=>server.listen(8765,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765');await page.locator('[data-country=PL]').click();await page.locator('[data-tab=achievements]').click();
 await page.evaluate(()=>{const peaks=catalog.places.filter(p=>p.country==='PL'&&p.mapReady&&p.category==='peak').slice(0,25);window.samplePeaks=peaks;visits=peaks.slice(0,24).map((p,i)=>({id:'sample-'+i,placeId:p.id,date:'2026-09-11',photos:[]}));syncAchievements();renderAchievements();});assert.equal(await page.locator('[data-badge=peak] [data-art-tier]').getAttribute('data-art-tier'),'1');assert.equal(await page.locator('[data-badge=peak] .progress').getAttribute('aria-valuenow'),'2');
 const bronze=await page.locator('[data-badge=peak] .rank-picture').innerHTML();await page.evaluate(()=>{visits.push({id:'sample-24',placeId:samplePeaks[24].id,date:'2026-09-11',photos:[]});localStorage.setItem('visits',JSON.stringify(visits));syncAchievements();renderAchievements();});assert.equal(await page.locator('[data-badge=peak] [data-art-tier]').getAttribute('data-art-tier'),'2');assert.equal(await page.locator('[data-badge=peak] .progress').getAttribute('aria-valuenow'),'3');assert.notEqual(await page.locator('[data-badge=peak] .rank-picture').innerHTML(),bronze);
 for(const theme of ['light','dark']){await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);await page.screenshot({path:path.join(out,`063-list-${theme}.png`)});await page.locator('[data-badge=peak]').click();await page.screenshot({path:path.join(out,`063-detail-${theme}.png`)});assert.match(await page.locator('.badge-target').innerText(),/Próg 3 - cel: 25 szczytów/);const art=await page.locator('.badge-hero').boundingBox(),target=await page.locator('.badge-target').boundingBox();assert(art.y+art.height<=target.y);await page.locator('#nextBadgeTier').click();assert.equal(await page.locator('.badge-hero [data-art-tier]').getAttribute('data-art-tier'),'3');await page.locator('[data-detail-close]').click();assert.equal(await page.locator('[data-badge=peak] [data-art-tier]').getAttribute('data-art-tier'),'2');}
 for(const family of ['peak','castle','cave','waterfall','explorer','distance','vertical','time','mustsee','regional','collections','country']){await page.locator(`[data-badge=${family}]`).click();for(const tier of [8,9,10]){await page.locator('.badge-all-tiers summary').click();await page.locator(`[data-tier="${tier}"]`).click();assert.equal(await page.locator('.badge-hero [data-rank-star]').count(),tier-7);assert.equal(await page.locator('.badge-hero .badge-level').innerText(),'Master '+(tier-7));if(family==='peak'&&tier===9){await page.screenshot({path:path.join(out,'063-master2-dark.png')});await page.setViewportSize({width:320,height:640});assert(await page.locator('#exploreDialog').evaluate(d=>d.scrollWidth<=d.clientWidth));await page.screenshot({path:path.join(out,'063-master2-320.png')});await page.setViewportSize({width:390,height:844});}}await page.locator('[data-detail-close]').click();}
 await page.reload();await page.locator('[data-tab=achievements]').click();assert.equal(await page.locator('[data-badge=peak] [data-art-tier]').getAttribute('data-art-tier'),'2');assert.deepEqual(errors,[]);await browser.close();server.close();console.log('PASS 0.6.3: earning tier 3 changes image and progress; vertical detail, next-tier preview, persistence; 1/2/3 vector stars across all 12 families; Light/Dark and 320px');
})().catch(e=>{console.error(e);process.exit(1)});
