const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const path=require('node:path'),http=require('node:http');
const assets=path.resolve(__dirname,'../app/src/main/assets/ui'),out=path.resolve(__dirname,'../build/ui-qa');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const file=path.resolve(assets,'.'+(new URL(req.url,'http://localhost').pathname==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));if(!file.startsWith(assets+path.sep)){res.writeHead(403).end();return;}try{const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json'};res.setHeader('Content-Type',mime[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{
 await new Promise(resolve=>server.listen(8765,'127.0.0.1',resolve));
 const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765');await page.locator('[data-country=PL]').click();await page.waitForTimeout(400);
 assert.equal(await page.locator('#fit').count(),0);assert.equal(await page.locator('.home-marker').count(),1);assert(await page.locator('#homePoint').innerText().then(x=>x.includes('Jastrzębie-Zdrój')));
 assert.equal(await page.evaluate(()=>layer.hasLayer(homeMarker)),false);
 assert.equal(await page.locator('.country-mask').count(),1);
 await page.getByRole('button',{name:'Lista',exact:true}).click();await page.locator('[data-place]').first().click();
 const popup=await page.locator('.leaflet-popup-content').innerText();assert(!/źródło|Punkt obszaru|\d{2}\.\d{5}/.test(popup));
 await page.locator('[data-visit-place]').click();await page.getByRole('button',{name:'Anuluj',exact:true}).click();assert.equal(await page.evaluate(()=>visits.length),0);
 await page.locator('[data-visit-place]').click();await page.locator('[name=date]').fill('2026-09-09');await page.selectOption('[name=weather]','Słonecznie');await page.fill('[name=notes]','Pierwsza wizyta <test>');await page.fill('[name=distance]','12.34');await page.fill('[name=duration]','185');await page.fill('[name=elevation]','700');await page.fill('[name=trailUrl]','Malinów → Skrzyczne <trasa>');assert.equal(await page.locator('#photoInput').count(),0);await page.screenshot({path:path.join(out,'visit-form.png')});
 await page.getByRole('button',{name:'Zapisz wizytę',exact:true}).click();assert.equal(await page.evaluate(()=>visits.length),1);assert.equal(await page.evaluate(()=>visits[0].distance_m),12340);const id=await page.evaluate(()=>visits[0].placeId);
 await page.check('#unvisited');assert.equal(await page.evaluate(id=>selectedPlaces().some(p=>p.id===id),id),false);assert.equal(await page.locator('.home-marker').count(),1);
 await page.reload();await page.locator('#search').waitFor();assert.equal(await page.evaluate(()=>visited.size),1);
 await page.locator('[data-tab=journal]').click();assert(await page.locator('.journal').innerText().then(x=>x.includes('Pierwsza wizyta <test>')));assert.equal(await page.locator('.journal img').count(),0);assert.equal(await page.evaluate(()=>visits[0].trailUrl),'Malinów → Skrzyczne <trasa>');assert.equal(await page.locator('.journal trasa').count(),0);
 await page.locator('[data-edit-visit]').click();await page.fill('[name=notes]','Poprawiona wizyta');await page.getByRole('button',{name:'Zapisz wizytę',exact:true}).click();assert.equal(await page.evaluate(()=>visits.length),1);
 await page.evaluate(id=>openVisit(id),id);await page.locator('[name=date]').fill('2026-09-10');await page.getByRole('button',{name:'Zapisz wizytę',exact:true}).click();assert.equal(await page.evaluate(()=>visits.length),2);assert.equal(await page.evaluate(()=>visited.size),1);await page.screenshot({path:path.join(out,'journal.png')});
 await page.getByRole('button',{name:'Ustawienia',exact:true}).click();assert.equal(await page.locator('#settings a').count(),0);await page.locator('#openLegal').click();assert(await page.locator('#legal').isVisible());await page.locator('#closeLegal').click();await page.locator('#closeSettings').click();
 await page.getByRole('button',{name:'Wybór kraju',exact:true}).click();assert(await page.locator('.coming-soon').innerText().then(t=>t==='More countries coming soon'));await page.locator('[data-country=DE]').click();await page.waitForTimeout(500);assert(await page.locator('#homePoint').innerText().then(x=>x.includes('Overath')));await page.screenshot({path:path.join(out,'germany-mask.png')});
 await page.locator('[data-tab=journal]').click();assert.equal(await page.locator('.journal article').count(),0);
 await page.setViewportSize({width:320,height:640});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.context().setOffline(true);await page.evaluate(()=>renderJournal());assert.equal(await page.evaluate(()=>visits.length),2);
 assert.deepEqual(errors,[]);console.log('PASS: country mask/HOME, popup, cancel/save/edit/multiple visits, persistence, hidden photos, plain-text route, legal settings, coming soon, 320px, offline journal');await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
