const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const path=require('node:path'),http=require('node:http');
const assets=path.resolve(__dirname,'../app/src/main/assets/ui'),out=path.resolve(__dirname,'../build/ui-qa');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const file=path.resolve(assets,'.'+(new URL(req.url,'http://localhost').pathname==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));if(!file.startsWith(assets+path.sep)){res.writeHead(403).end();return;}try{const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json'};res.setHeader('Content-Type',mime[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{
 await new Promise(resolve=>server.listen(8765,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765');await page.locator('[data-country=PL]').click();await page.locator('[data-tab=collections]').click();await page.locator('[data-collection=PL-peak]').waitFor();await page.screenshot({path:path.join(out,'stage4-collections-light.png')});await page.locator('[data-collection=PL-peak]').click();
 const first=await page.locator('[data-detail-place]').last().getAttribute('data-detail-place');await page.locator('[data-detail-place]').last().click();await page.locator('#exploreDialog [data-visit-place]').click();await page.getByRole('button',{name:'Zapisz wizytę',exact:true}).click();assert(await page.locator('#exploreDialog').innerText().then(t=>t.includes('Odwiedzone')));await page.locator('[data-detail-close]').click();assert.equal(await page.locator('[data-detail-place]').first().getAttribute('data-detail-place'),first);assert.equal(await page.locator('.collections [role=progressbar]').getAttribute('aria-valuenow'),'1');
 await page.fill('#collectionSearch','xyzmissing');assert(await page.locator('#collectionMembers').innerText().then(t=>t.includes('Brak')));await page.fill('#collectionSearch','');await page.locator('[data-detail-place]').first().click();await page.locator('[data-show-map]').click();await page.waitForTimeout(300);assert(await page.locator('.leaflet-popup-content').isVisible());
 await page.locator('[data-tab=collections]').click();await page.locator('#backCollections').click();await page.locator('[data-collection-mode=peaks]').click();assert(await page.locator('[data-collection]').count()>10);
 await page.locator('[data-collection-mode=plans]').click();await page.locator('[data-plan=PL-malinow-skrzyczne]').click();assert.deepEqual(await page.locator('.visit-order strong').allTextContents(),['Malinów','Jaskinia Malinowska','Małe Skrzyczne','Skrzyczne']);await page.screenshot({path:path.join(out,'stage4-proposal.png')});
 await page.locator('[data-edit-plan]').click();await page.locator('#planTitle').fill('Moja lista <PL>');await page.locator('[data-move-index="1"][data-delta="-1"]').click();await page.locator('[data-remove-index="3"]').click();await page.fill('#planSearch','Malinowska Skała');await page.locator('[data-add-plan]').click();assert.equal(await page.locator('[data-add-plan]').count(),0);await page.locator('#savePlan').click();assert.equal(await page.evaluate(()=>plans.length),1);assert.equal(await page.locator('.visit-order strong').first().innerText(),'Jaskinia Malinowska');await page.locator('[data-detail-place]').first().click();await page.locator('[data-detail-back]').click();assert.equal(await page.locator('.visit-order strong').count(),4);await page.locator('[data-detail-close]').click();
 await page.reload();await page.locator('[data-tab=collections]').click();await page.locator('[data-collection-mode=plans]').click();assert.equal(await page.locator('[data-plan^="user-"]').count(),1);await page.locator('[data-plan^="user-"]').click();await page.locator('[data-edit-plan]').click();await page.fill('#planTitle','Zmieniona lista');await page.locator('#savePlan').click();assert.equal(await page.evaluate(()=>plans.length),1);await page.locator('[data-detail-close]').click();
 await page.locator('#newPlan').click();await page.locator('#savePlan').click();assert(await page.locator('#planError').innerText());await page.locator('[data-detail-close]').click();
 await page.getByRole('button',{name:'Ustawienia',exact:true}).click();await page.getByRole('button',{name:'Dark',exact:true}).click();await page.locator('#closeSettings').click();await page.screenshot({path:path.join(out,'stage4-plans-dark.png')});
 await page.getByRole('button',{name:'Wybór kraju',exact:true}).click();await page.locator('[data-country=DE]').click();await page.locator('[data-tab=collections]').click();assert.equal(await page.locator('[data-plan^="user-"]').count(),0);await page.locator('#newPlan').click();await page.fill('#planTitle','Harz');await page.fill('#planSearch','Brocken');await page.locator('[data-add-plan]').first().click();await page.fill('#planSearch','Brockengarten');await page.locator('[data-add-plan]').click();await page.locator('#savePlan').click();assert.equal(await page.evaluate(()=>plans.length),2);await page.locator('[data-delete-plan]').click();await page.locator('#confirmDeletePlan').click();assert.equal(await page.evaluate(()=>plans.length),1);assert.equal(await page.evaluate(()=>visits.length),1);
 await page.setViewportSize({width:320,height:640});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.context().setOffline(true);await page.locator('[data-collection-mode=theme]').click();assert(await page.locator('[data-collection]').count()>0);assert.deepEqual(errors,[]);console.log('PASS: collection progress and sorting, search, place-to-map, peak groups, exact proposal order, create/edit/reorder/remove/persist lists, no duplicates, country isolation, delete preserves visits, mobile and offline');await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
