const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const path=require('node:path'),http=require('node:http');
const assets=path.resolve(__dirname,'../app/src/main/assets/ui'),out=path.resolve(__dirname,'../build/ui-qa');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const file=path.resolve(assets,'.'+(new URL(req.url,'http://localhost').pathname==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));if(!file.startsWith(assets+path.sep)){res.writeHead(403).end();return;}try{const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json'};res.setHeader('Content-Type',mime[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{
 await new Promise(resolve=>server.listen(8765,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8765');await page.locator('[data-country=PL]').click();const id=await page.evaluate(()=>catalog.places.find(p=>p.country==='PL'&&p.mapReady).id);
 await page.evaluate(id=>openVisit(id),id);await page.locator('[data-rating="4"]').click();await page.getByRole('button',{name:'Zapisz wizytę',exact:true}).click();await page.locator('[data-tab=journal]').click();assert.equal(await page.locator('.journal-rating').getAttribute('aria-label'),'Ocena 4 z 5');assert.equal(await page.locator('.journal-rating').innerText(),'★★★★☆');assert.equal(await page.locator('.journal-symbol svg').count(),1);assert(await page.locator('.visit-date').innerText());
 await page.reload();await page.locator('[data-tab=journal]').click();assert.equal(await page.locator('.journal-rating').getAttribute('aria-label'),'Ocena 4 z 5');await page.locator('[data-edit-visit]').click();assert.equal(await page.locator('[data-rating="4"]').getAttribute('aria-pressed'),'true');await page.locator('[data-rating="5"]').click();await page.getByRole('button',{name:'Zapisz wizytę',exact:true}).click();assert.equal(await page.locator('.journal-rating').getAttribute('aria-label'),'Ocena 5 z 5');
 await page.evaluate(id=>openVisit(id),id);await page.getByRole('button',{name:'Zapisz wizytę',exact:true}).click();assert.equal(await page.locator('.journal-rating[aria-label="Bez oceny"]').count(),1);await page.screenshot({path:path.join(out,'journal-ratings-light.png')});
 await page.locator('[data-delete-visit]').first().click();await page.locator('#cancelDeleteVisit').click();assert.equal(await page.evaluate(()=>visits.length),2);
 // A failed native write must not remove UI data or alter progress.
 await page.evaluate(()=>{window.Passport={deleteVisit:()=>'{"ok":false}'};});await page.locator('[data-delete-visit]').first().click();await page.locator('#confirmDeleteVisit').click();assert(await page.locator('#deleteVisitError').innerText());assert.equal(await page.evaluate(()=>visits.length),2);await page.locator('#cancelDeleteVisit').click();await page.evaluate(()=>delete window.Passport);
 await page.locator('[data-delete-visit]').first().click();await page.locator('#confirmDeleteVisit').click();assert.equal(await page.evaluate(()=>visits.length),1);assert.equal(await page.evaluate(()=>visited.size),1);
 await page.locator('[data-tab=collections]').click();await page.locator('[data-collection=PL-peak]').click();await page.fill('#collectionSearch','Barania');await page.locator('[data-tab=journal]').click();await page.locator('[data-tab=collections]').click();assert.equal(await page.locator('#collectionSearch').count(),0);assert(await page.locator('[data-collection=PL-peak]').isVisible());assert.equal(await page.locator('[data-collection=PL-peak] [role=progressbar]').getAttribute('aria-valuenow'),'1');
 await page.locator('[data-tab=journal]').click();await page.getByRole('button',{name:'Ustawienia',exact:true}).click();await page.getByRole('button',{name:'Dark',exact:true}).click();await page.locator('#closeSettings').click();await page.screenshot({path:path.join(out,'journal-ratings-dark.png')});
 await page.locator('[data-edit-visit]').click();await page.locator('#clearRating').click();await page.getByRole('button',{name:'Zapisz wizytę',exact:true}).click();assert.equal(await page.locator('.journal-rating').getAttribute('aria-label'),'Bez oceny');
 await page.locator('[data-delete-visit]').click();await page.locator('#confirmDeleteVisit').click();assert.equal(await page.evaluate(()=>visits.length),0);assert.equal(await page.evaluate(()=>visited.size),0);assert(await page.locator('.journal').innerText().then(t=>t.includes('Jeszcze nie masz')));await page.reload();await page.locator('[data-tab=collections]').click();assert.equal(await page.locator('[data-collection=PL-peak] [role=progressbar]').getAttribute('aria-valuenow'),'0');await page.locator('[data-tab=map]').click();await page.check('#unvisited');assert.equal(await page.evaluate(id=>selectedPlaces().some(p=>p.id===id),id),true);
 await page.setViewportSize({width:320,height:640});await page.evaluate(id=>openVisit(id),id);assert(await page.evaluate(()=>document.querySelector('#visitDialog').scrollWidth<=document.querySelector('#visitDialog').clientWidth));assert.deepEqual(errors,[]);console.log('PASS: ratings 1–5/clear/edit/persist, journal symbol/date/rating, cancellation and failed delete, delete one vs last, progress/filter rollback, collection navigation reset, 320px');await browser.close();server.close();
})().catch(e=>{console.error(e);process.exit(1)});
