const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs');
const path=require('node:path'),http=require('node:http');
const assets=path.resolve(__dirname,'../app/src/main/assets/ui'),out=path.resolve(__dirname,'../build/ui-qa');fs.mkdirSync(out,{recursive:true});
const server=http.createServer((req,res)=>{const file=path.resolve(assets,'.'+(new URL(req.url,'http://localhost').pathname==='/'?'/index.html':new URL(req.url,'http://localhost').pathname));if(!file.startsWith(assets+path.sep)){res.writeHead(403).end();return;}try{const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.json':'application/json'};res.setHeader('Content-Type',mime[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
(async()=>{
 await new Promise(resolve=>server.listen(8765,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8765');await page.locator('[data-country=PL]').click();
 assert.deepEqual(await page.locator('[data-tab]').evaluateAll(bs=>bs.map(b=>b.dataset.tab)),['map','journal','collections','achievements']);
 const id=await page.evaluate(()=>catalog.places.find(p=>p.country==='PL'&&p.mapReady&&p.category==='castle').id);
 await page.evaluate(id=>openVisit(id),id);assert.equal(await page.locator('[name=distance], [name=trailUrl], #addPhoto').count(),0);await page.fill('[name=date]','2026-08-01');await page.selectOption('[name=weather]','Śnieg');await page.locator('[data-rating="4"]').click();await page.fill('[name=notes]','Zamek <img src=x onerror=alert(1)>');await page.locator('#visitForm [type=submit]').click();
 await page.locator('[data-tab=journal]').click();assert.equal(await page.locator('.visit-date').innerText(),'2026-08-01');assert.equal(await page.locator('.journal-weather').first().getAttribute('aria-label'),'Śnieg');assert.equal(await page.locator('.journal img').count(),0);
 // Editing a legacy non-peak visit preserves hidden metrics, route and attachments.
 await page.evaluate(()=>{Object.assign(visits[0],{distance_m:1234,duration_minutes:60,elevation_gain_m:90,trailUrl:'Stara trasa',photos:['legacy.jpg']});openVisit(visits[0].placeId,visits[0]);});await page.fill('[name=date]','2026-08-02');await page.locator('#visitForm [type=submit]').click();assert.deepEqual(await page.evaluate(()=>[visits[0].date,visits[0].distance_m,visits[0].duration_minutes,visits[0].elevation_gain_m,visits[0].trailUrl,visits[0].photos]),['2026-08-02',1234,60,90,'Stara trasa',['legacy.jpg']]);assert.equal(await page.locator('.journal-route').count(),0);
 await page.evaluate(id=>openVisit(id),id);await page.fill('[name=date]','2026-09-01');await page.locator('[data-rating="2"]').click();await page.locator('#visitForm [type=submit]').click();assert.equal(await page.locator('.journal article').count(),2);
 await page.selectOption('#journalRating','4');assert.equal(await page.locator('.journal article').count(),1);await page.fill('#journalDate','2026-09-01');await page.locator('#journalDate').dispatchEvent('change');assert.equal(await page.locator('.journal article').count(),0);assert.equal(await page.evaluate(()=>visits.length),2);await page.locator('#resetJournalFilters').click();await page.selectOption('#journalSort','oldest');assert.equal(await page.locator('.visit-date').first().innerText(),'2026-08-02');await page.selectOption('#journalSort','rating');assert.equal(await page.locator('.journal-rating').first().innerText(),'★★★★☆');
 await page.screenshot({path:path.join(out,'062-journal-dark.png')});await page.reload();await page.locator('[data-tab=journal]').click();assert.equal(await page.locator('.journal article').count(),2);
 const fresh=await context.newPage();await fresh.goto('http://127.0.0.1:8765');await fresh.locator('[data-country=PL]').waitFor();assert.equal(await fresh.evaluate(()=>visits.length),2);await fresh.close();
 await page.locator('[data-tab=achievements]').click();assert.equal(await page.locator('[data-badge]').count(),12);assert.equal(await page.locator('[data-badge=castle] [role=progressbar]').getAttribute('aria-valuemax'),'11');await page.locator('[data-badge=peak]').click();assert.match(await page.locator('.badge-detail-progress').innerText(),/5 szczytów/);assert(await page.locator('.badge-description').innerText());assert.equal(await page.evaluate(()=>badgeUnit(achievementData.families.find(f=>f.id==='castle'),1)),'zamek');await page.screenshot({path:path.join(out,'062-badge-dark.png')});
 await page.setViewportSize({width:320,height:640});for(const theme of ['light','dark']){await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);assert(await page.locator('#exploreDialog').evaluate(d=>d.scrollWidth<=d.clientWidth));await page.screenshot({path:path.join(out,`062-badge-${theme}-320.png`)});}await page.locator('[data-detail-close]').click();await page.screenshot({path:path.join(out,'062-badges-dark.png')});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 await browser.close();server.close();console.log('PASS 0.6.2: non-peak date, hidden-field preservation, icons, date/rating filters, sorting, cold session, navigation, badge units and compact layout');
})().catch(e=>{console.error(e);process.exit(1)});
